# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28c40185fd4a3f6fa019120cf26d09939ffdea63c7235479a3d7f0822cff6dd578d4fe7646a205acefd30324a783dd73960ddabd69fb89d14e6f02f700bc2aab

test:
  secret_key_base: b2db3119bb8c06c3bf3b4d624e74a2f439f3ceb952dcaaa3634385f116e1a38eba54b4150c8741026ecfc4295212d95ade408d994fdf373c274456929f65ec0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
